### ISSUE TITLE
[Bug]: <Fix argocd link in the `idpbuilder create` output in codespace>

### ISSUE THREAD

**Issue by SupriyaNallapeta** [cnoe-io/idpbuilder#269]
### What is your environment, configuration, and command?

running idpbuilder create command in the Codespace as explained the README. 

### What did you do and What did you see instead?

In the codespace, the idpbuilder create command will give the invalid argocd url with port appended similar to this

```
Can Access ArgoCD at http://verbose-broccoli-jr5j59g5j7wh56x4-8080.app.github.dev:8080/argocd
Username: admin
Password can be retrieved by running: idpbuilder get secrets -p argocd
```

I would expect to see it as below,
```
Can Access ArgoCD at http://verbose-broccoli-jr5j59g5j7wh56x4-8080.app.github.dev/argocd
Username: admin
Password can be retrieved by running: idpbuilder get secrets -p argocd
```

related code:  https://github.com/cnoe-io/idpbuilder/blob/main/pkg/cmd/create/root.go#L134
https://github.com/cnoe-io/idpbuilder/pull/267#discussion_r1619452434

**Comment by nimakaviani** [comment]
Closing this, as it was discussed and fixed in #267

**Comment by nabuskey** [comment]
Not fixed actually. If you run this in codespaces environment, the printed url at the end is incorrect. Specifically the port. This is not a codespaces specific problem either. If you are fronting this with another proxy, this problem applies. I'd imagine this will be relevant when deploying to remote clusters as well.
