### ISSUE TITLE
[Bug]: GitRepository.idpbuilder.cnoe.io "argocd" is invalid: spec.provider.gitURL: Invalid value: "": spec.provider.gitURL in body should match '^https?:\/\/.+$' 

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#425]
## Issue

When we create a new new cluster (using podman as container engine), we got different errors

Command used:
```
KIND_EXPERIMENTAL_PROVIDER=podman idpbuilder create \
        --color \
        --build-name konflux \
        --recreate
```

## Errors

We have potentially several issues OR one having the following side effects here:

### Error 1 - `spec.provider.gitURL: Invalid value`

`
Oct 24 09:09:13 ERROR Reconciler error controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=332f25c8-136d-465b-b517-db93baa3defd err=reconciling bootstrap apps creating argocd repo CR: GitRepository.idpbuilder.cnoe.io "argocd" is invalid: spec.provider.gitURL: Invalid value: "": spec.provider.gitURL in body should match '^https?:\/\/.+$'
`
![Screenshot 2024-10-24 at 09 32 11](https://github.com/user-attachments/assets/02c3d717-c82c-4d9f-a8f2-7e6c91833a41)

### Error 2 - `panic: runtime error: invalid memory address or nil pointer dereference`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101ab2c8c]

goroutine 948 [running]:
code.gitea.io/sdk/gitea.(*Client).SetBasicAuth(0x0, {0x14001484310, 0xa}, {0x14000d4f0b0, 0x28})
        /Users/cmoullia/go/pkg/mod/code.gitea.io/sdk/gitea@v0.16.0/client.go:168 +0x2c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.getGiteaToken({0x1025e84b0, 0x140000d6730}, {0x140011d3d10, 0x24}, {0x14001484310, 0xa}, {0x14000d4f0b0, 0x28})
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:183 +0x18c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).setGiteaToken(_, {_, _}, {{{0x1020e42c7, 0x6}, {0x101c863bc, 0x2}}, {{0x14000734920, 0x10}, {0x0, ...}, ...}, ...}, ...)
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:166 +0x198
```

### Error 3 - Timeout
```
Oct 24 08:17:35 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=bb8dd1fb-c992-4470-9faa-0acf53bf5734 
Oct 24 08:17:40 INFO installing bootstrap apps to ArgoCD controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=063c7301-b510-42fd-bc4a-852fc90ab0b9 
Oct 24 08:17:40 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=063c7301-b510-42fd-bc4a-852fc90ab0b9 
Oct 24 08:17:48 ERROR Reconciler error controller=gitrepository controllerGroup=idpbuilder.cnoe.io controllerKind=GitRepository name=argocd namespace=idpbuilder-konflux namespace=idpbuilder-konflux name=argocd reconcileID=b0376a2d-e967-4c8c-a046-beb44c0af4de err=initializing git provider: Get "https://gitea.cnoe.localtest.me:8443/api/v1/version": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
O
```
![Screenshot 2024-10-24 at 08 14 20](https://github.com/user-attachments/assets/9f4583c6-b064-4075-85e2-6b50146fe159)

### Error 4 - tls
```
Oct 24 09:22:49 ERROR Reconciler error controller=gitrepository controllerGroup=idpbuilder.cnoe.io controllerKind=GitRepository name=argocd namespace=idpbuilder-konflux namespace=idpbuilder-konflux name=argocd reconcileID=a1caaf98-bda9-4cce-ad00-4c9f53ecc407 err=updating repository contents: pushing to git: Get "https://gitea.cnoe.localtest.me:8443/giteaAdmin/idpbuilder-konflux-argocd.git/info/refs?service=git-receive-pack": net/http: TLS handshake timeout 
```

## Tests

I did a couple of tests on MacOS - ARM64 using either podman or docker locally and here is what I oberserved

### Docker

Docker client: 27.2.0
Docker engine: 4.34.2
where the VM has 12 CPU and max 12 GB of RAM

I didn't get such errors when I created 2 times a cluster

### Podman
Podman engine (uses AppleHV): 5.0.3
Podman Client: 5.2.4

I got the errors reported here using: CPU: 6 and Max memory 8 GB of RAM

I din't get the errors except one time the `error 1` using CPU: 12 and memory 12 GB of RAM

**Comment by cmoulliard** [comment]
All the PODS have been well created !
![Screenshot 2024-10-23 at 19 02 05](https://github.com/user-attachments/assets/3656a1fa-021a-43fc-910a-b26f7518a178)

**Comment by cmoulliard** [comment]
I think that we have an issue when se set the gitea auth
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101ab2c8c]

goroutine 948 [running]:
code.gitea.io/sdk/gitea.(*Client).SetBasicAuth(0x0, {0x14001484310, 0xa}, {0x14000d4f0b0, 0x28})
        /Users/cmoullia/go/pkg/mod/code.gitea.io/sdk/gitea@v0.16.0/client.go:168 +0x2c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.getGiteaToken({0x1025e84b0, 0x140000d6730}, {0x140011d3d10, 0x24}, {0x14001484310, 0xa}, {0x14000d4f0b0, 0x28})
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:183 +0x18c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).setGiteaToken(_, {_, _}, {{{0x1020e42c7, 0x6}, {0x101c863bc, 0x2}}, {{0x14000734920, 0x10}, {0x0, ...}, ...}, ...}, ...)
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:166 +0x198
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).ReconcileGitea(0x14000528960, {0x1025e84b0, 0x140000d6730}, {{{0x0?, 0x0?}, {0x0?, 0x0?}}}, 0x14000c27a00)
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:132 +0x898
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).installCorePackages.func1()
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/controller.go:118 +0xa8
created by github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).installCorePackages in goroutine 817
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/controller.go:116 +0x340
```

**Comment by cmoulliard** [comment]
This issue is intermittent as a few hours after I experimented it, the cluster can be created now !

**Comment by cmoulliard** [comment]
Sometimes the error occurs directly
```
~/code/ch007m/my-konflux on main •
❯ KIND_EXPERIMENTAL_PROVIDER=podman idpbuilder create \
        --color \
        --build-name konflux \
        --recreate
Oct 23 21:08:12 INFO Creating kind cluster logger=setup 
Oct 23 21:08:12 INFO Runtime detected logger=setup provider=podman 
Oct 23 21:08:13 INFO Existing cluster found. Deleting. logger=setup cluster=konflux 
########################### Our kind config ############################
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:v1.30.0"
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitea.cnoe.localtest.me:8443"]
    endpoint = ["https://gitea.cnoe.localtest.me"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."gitea.cnoe.localtest.me".tls]
    insecure_skip_verify = true
#########################   config end    ############################
Oct 23 21:08:24 INFO Creating kind cluster logger=setup cluster=konflux 
Oct 23 21:08:38 INFO Done creating cluster logger=setup cluster=konflux 
Oct 23 21:08:39 INFO Adding CRDs to the cluster logger=setup 
Oct 23 21:08:39 INFO Setting up CoreDNS logger=setup 
Oct 23 21:08:39 INFO Setting up TLS certificate logger=setup 
Oct 23 21:08:40 INFO Creating localbuild resource logger=setup 
Oct 23 21:08:40 INFO Starting EventSource controller=gitrepository controllerGroup=idpbuilder.cnoe.io controllerKind=GitRepository source=kind source: *v1alpha1.GitRepository 
Oct 23 21:08:40 INFO Starting Controller controller=gitrepository controllerGroup=idpbuilder.cnoe.io controllerKind=GitRepository 
Oct 23 21:08:40 INFO Starting EventSource controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild source=kind source: *v1alpha1.Localbuild 
Oct 23 21:08:40 INFO Starting EventSource controller=custompackage controllerGroup=idpbuilder.cnoe.io controllerKind=CustomPackage source=kind source: *v1alpha1.CustomPackage 
Oct 23 21:08:40 INFO Starting Controller controller=custompackage controllerGroup=idpbuilder.cnoe.io controllerKind=CustomPackage 
Oct 23 21:08:40 INFO Starting Controller controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild 
Oct 23 21:08:40 INFO Starting workers controller=custompackage controllerGroup=idpbuilder.cnoe.io controllerKind=CustomPackage worker count=1 
Oct 23 21:08:40 INFO Starting workers controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild worker count=1 
Oct 23 21:08:40 INFO Starting workers controller=gitrepository controllerGroup=idpbuilder.cnoe.io controllerKind=GitRepository worker count=1 
Oct 23 21:08:42 INFO Waiting for Deployment ingress-nginx-controller to become ready controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=c1d08ea0-536c-4295-b2df-5957df327093 
Oct 23 21:08:52 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=c1d08ea0-536c-4295-b2df-5957df327093 
Oct 23 21:08:52 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=e0641993-0fea-4b31-bf26-1634e9e67bc3 
Oct 23 21:08:57 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=07cf02cd-87da-44ae-9b6f-6f68a331ab07 
Oct 23 21:09:02 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=45b2b341-a93a-4908-b6be-753d798a3d7a 
Oct 23 21:09:07 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=89dd0aa1-5994-43d9-84a5-d923aa512b3b 
Oct 23 21:09:12 INFO Checking if we should shutdown controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=aff6b621-ee63-44c8-bb31-0be44e36faf0 
Oct 23 21:09:12 INFO Waiting for Deployment ingress-nginx-controller to become ready controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=c1d08ea0-536c-4295-b2df-5957df327093 
Oct 23 21:09:17 INFO Waiting for Deployment my-gitea to become ready controller=localbuild controllerGroup=idpbuilder.cnoe.io controllerKind=Localbuild name=konflux name=konflux reconcileID=48de16e5-26d5-4e1c-8ef6-4a31f546475e 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10142acec]

goroutine 87 [running]:
code.gitea.io/sdk/gitea.(*Client).SetBasicAuth(0x0, {0x14001a00ef0, 0xa}, {0x14001090a20, 0x28})
        /Users/cmoullia/go/pkg/mod/code.gitea.io/sdk/gitea@v0.19.0/client.go:174 +0x2c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.getGiteaToken({0x101f616f0, 0x1400070c0f0}, {0x14000682c60, 0x24}, {0x14001a00ef0, 0xa}, {0x14001090a20, 0x28})
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:183 +0x18c
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).setGiteaToken(_, {_, _}, {{{0x101a5c2ea, 0x6}, {0x1016004fc, 0x2}}, {{0x1400171e3e0, 0x10}, {0x0, ...}, ...}, ...}, ...)
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:166 +0x198
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).ReconcileGitea(0x1400043a960, {0x101f616f0, 0x1400070c0f0}, {{{0x0?, 0x0?}, {0x14000029510?, 0x7?}}}, 0x14000ce0600)
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/gitea.go:132 +0x898
github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).installCorePackages.func1()
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/controller.go:118 +0xa8
created by github.com/cnoe-io/idpbuilder/pkg/controllers/localbuild.(*LocalbuildReconciler).installCorePackages in goroutine 86
        /Users/cmoullia/code/cnoe/fork-idpbuilder/pkg/controllers/localbuild/controller.go:116 +0x340
```

**Comment by nabuskey** [comment]
Hmm this isn't good. Looks like we are not checking for nil somehow. We will have to investigate.

**Comment by nabuskey** [comment]
```
spec.provider.gitURL: Invalid value
```
This is usually harmless. It just means the Gitea repository is not ready and do not have an repository to associate yet. We can improve logging here.

For nil ref, gitea.NewClient apparently calls the server. Under situations with resource contentions, this could return nil. We shouldn't call that function.

**Comment by nabuskey** [comment]
Nil ref should be fixed now. Errors three and four seem to be related to resource contentions where we cannot get the response we need in reasonable time. We assume gitea and k8s can respondin 30 seconds per request.

**Comment by cmoulliard** [comment]
I did some tests on a Virtual VM (on ly macos) having 8GB of RAM and 6 CPU and using your fix (= Git Client) and didn't get anymore the errors 2, 3. 

**Remark**: Error 1 still happens but is not blocking. A better log message should help the users @nabuskey to understand what it happens under the hood

@nabuskey

**Comment by cmoulliard** [comment]
I will close this ticket as fixed and another ticket exists also to better log the message
