### ISSUE TITLE
[Bug]: Release job fails - Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/idpbuilder#479]
## Issue

The job to release fails: https://github.com/cnoe-io/idpbuilder/actions/runs/12945012192/job/36106860618 during the step of the flow to `     `Generate a homebrew tap update token`

```
7s
Run actions/create-github-app-token@v1
owner and repositories not set, creating token for the current repository ("idpbuilder")
Failed to create token for "idpbuilder" (attempt 1): [universal-github-app-jwt] Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
Failed to create token for "idpbuilder" (attempt 2): [universal-github-app-jwt] Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
Failed to create token for "idpbuilder" (attempt 3): [universal-github-app-jwt] Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
Failed to create token for "idpbuilder" (attempt 4): [universal-github-app-jwt] Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
Error: [universal-github-app-jwt] Private Key is in OpenSSH format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
    at getToken (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:38662:11)
    at githubAppJwt (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:38705:23)
    at getAppAuthentication (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:38868:37)
    at hook4 (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39166:37)
    at newApi (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:37967:36)
    at getTokenFromRepository (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39491:26)
    at /home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39436:13
    at RetryOperation._fn (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:39359:30)
    at Timeout.<anonymous> (/home/runner/work/_actions/actions/create-github-app-token/v1/dist/main.cjs:19869:14)
    at listOnTimeout (node:internal/timers:581:17) {
  attemptNumber: 4,
  retriesLeft: 0
```

### What did you do and What did you see instead?

See job action

**Comment by cmoulliard** [comment]
Can one of the ADMIN have a look https://github.com/actions/create-github-app-token and check if a GITHUB_APP has been created and if the needed AP_IP and KEY have been set ?
@nabuskey

**Comment by nabuskey** [comment]
No idea how this is set up. From my initial look, `HOMEBREW_TOKEN` referenced in the go releaser file is not defined anywhere. 

The github token / app stuff does work.

**Comment by cmoulliard** [comment]
> The github token / app stuff does work.

Remark: An `app_id` exists and is listed when the action `actions/create-github-app-token@v1` runs => `911161`

As I don't have access to the settings of this github repository, can you then check if a secret exists for `CNOE_HOMEBREW_PRIVATE_KEY` and is in format `PKCS#1`

@nabuskey

**Comment by nabuskey** [comment]
it does exist but I can't verify its format. GH doesn't allow you to view secrets. You can only replace them.

Our release process is broken now. I suggest removing homebrew section for now. Test it and make sure it works first, then re-enable it.

**Comment by cmoulliard** [comment]
I did a test on my project successfully. I suspect that either the Github App has not been created correctly OR the PRIVATE_KEY has not been created using the proper format

Action: https://github.com/ch007m/go-helloworld/actions/runs/13012337516/job/36292843784
My Workflow
```
name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Generate a homebrew tap update token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GORELEASER_HOMEBREW_APP_ID }}
          private-key: ${{ secrets.GORELEASER_HOMEBREW_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ steps.generate-token.outputs.token }}
```
GoReleaser
```
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

# https://goreleaser.com/customization/project/
# Name used prefix of the executable name created by the archive module
project_name: hello

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# https://goreleaser.com/cookbooks/builds-complex-envs/?h=builds
builds:
  - id: linux
    binary: hello
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

  - id: osx
    binary: hello
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

  - id: windows
    binary: hello
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

# https://goreleaser.com/customization/archive/?h=archives
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# https://goreleaser.com/customization/checksum/?h=checksum
checksum:
  name_template: "checksums.sha256"

# https://goreleaser.com/customization/changelog/?h=changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/?h=homebrew
brews:
  - name: hello
    repository:
      owner: ch007m
      name: homebrew-helloworld
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: ch007m
      email: cmoulliard@redhat.com
    directory: Formula
    #homepage: https://cnoe.io/
    description: "Go HelloWorld example"
    #test: |
    #  system "idpbuilder version"

# https://goreleaser.com/customization/release/#release
release:
  target_commitish: '{{ .Commit }}'
  footer: >-
    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

```

**Comment by nabuskey** [comment]
@punkwalker Can you take a look at this please.

**Comment by punkwalker** [comment]
@cmoulliard  
This issue of Key format is fixed. It was due to missing GH App private key in `CNOE_HOMEBREW_PRIVATE_KEY` secret. Instead it was a GitHUb App client secret, therefore the `create-token action` was complaining about the format. 

So I updated the secret and re-ran the job which went past the key format issue but ran into issue while publishing the homebrew formula to `hombrew-tap` repo. For this, I created a PR which would allow `create-token action` to generate a token for `hombrew-tap` repo.

**Comment by cmoulliard** [comment]
There is still an issue during the execution of the release job : https://github.com/cnoe-io/idpbuilder/actions/runs/13005396513/job/36310567450 @punkwalker

**Comment by punkwalker** [comment]
@cmoulliard Yes. The existing failed runs are not using latest workflow file.
And We can't trigger a new run for release so we have to wait till tonight.
